### ISSUE TITLE
Set document.title

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#89]
All Parchment tabs have the same title, "Parchment." Parchment should set `document.title` to the title of the game, once it's discovered.

**Comment by curiousdannii** [comment]
Yep. Included as part of #72, but it's fine for this to be its own issue

**Comment by dfabulich** [comment]
This got fixed at some point.

**Comment by curiousdannii** [comment]
Well it's fixed on the server, but not if you run it locally, or if you upload a storyfile into Parchment. Those could still have their titles changed.
